### ISSUE TITLE
New User Registration

### ISSUE THREAD

**Issue by wonderfloyd** [wonderfloyd/Consenz_TE0#1]
אהרון: לא הצלחתי להירשם באמצעות אימייל וסיסמה (לוגין עם גוגל עבד חלק)

**Comment by wonderfloyd** [comment]
https://consenz-test-environment-0.firebaseapp.com/#/

**Comment by reut-soficoop** [comment]
<img width="1440" alt="Screen Shot 2019-12-02 at 15 53 41" src="https://user-images.githubusercontent.com/42338952/69945395-08418280-151c-11ea-8ab8-51712cf906f6.png">

**Comment by reut-soficoop** [comment]
SOLVED!
<img width="1440" alt="Screen Shot 2019-12-02 at 15 56 11" src="https://user-images.githubusercontent.com/42338952/69945529-4d65b480-151c-11ea-95c7-dd74305a2fe5.png">

**Comment by wonderfloyd** [comment]
Better that Aharon closes the issue
