### ISSUE TITLE
Bug - new section suggestions does not load

### ISSUE THREAD

**Issue by Aharon-Porath** [wonderfloyd/Consenz_TE0#15]
![image](https://user-images.githubusercontent.com/5900841/71208013-d0269780-22b0-11ea-8580-1a49c848e13c.png)

**Comment by yatuvy** [comment]
this only happens in mock-data_yonatan branch,
I'll fix it

**Comment by yatuvy** [comment]
please check again, and do overall tests again

**Comment by Aharon-Porath** [comment]
This one fixed, the other open issues not yet.
