### ISSUE TITLE
After adding an argument, go to 'New Argument View'

### ISSUE THREAD

**Issue by wonderfloyd** [wonderfloyd/Consenz_TE0#3]
אהרון: אחרי הוספת טיעון חדש לא הועברתי לתצוגת הטיעון החדש (הטיעון פורסם אבל לא התקבל הפידבק הרצוי)

**Comment by wonderfloyd** [comment]
https://consenz-test-environment-0.firebaseapp.com/#/

**Comment by reut-soficoop** [comment]
SOLVED!
<img width="1440" alt="Screen Shot 2019-12-02 at 15 59 07" src="https://user-images.githubusercontent.com/42338952/69945714-b9481d00-151c-11ea-89d8-e76c47afb79b.png">
<img width="1440" alt="Screen Shot 2019-12-02 at 15 59 54" src="https://user-images.githubusercontent.com/42338952/69945763-d5e45500-151c-11ea-91a0-d0c1658742a9.png">
