### ISSUE TITLE
Pressing "I'm convinced" should count as a Vote

### ISSUE THREAD

**Issue by wonderfloyd** [wonderfloyd/Consenz_TE0#4]
אהרון: לחיצה על "השתכנעתי" לטיעון אמורה להיחשב גם כהצבעה בהתאם (הצבעת בעד לטיעון בעד, נגד לנגד). לפעמים זה עובד ולפעמים לא.

**Comment by wonderfloyd** [comment]
https://consenz-test-environment-0.firebaseapp.com/#/

**Comment by Aharon-Porath** [comment]
Before: 
![image](https://user-images.githubusercontent.com/5900841/69903021-e7065800-139c-11ea-8ecb-fbab8af5fd55.png)

After:
![image](https://user-images.githubusercontent.com/5900841/69903019-deae1d00-139c-11ea-8757-37d333e21687.png)

**Comment by Aharon-Porath** [comment]
Before (voting con):
![image](https://user-images.githubusercontent.com/5900841/69903030-02716300-139d-11ea-9df1-2203f49e558c.png)

After:
![image](https://user-images.githubusercontent.com/5900841/69903033-0ac99e00-139d-11ea-85d6-9f1612730a59.png)
