### ISSUE TITLE
Missing original text in 'Change Section View'

### ISSUE THREAD

**Issue by wonderfloyd** [wonderfloyd/Consenz_TE0#5]
אהרון: במסך הצעה לשינוי סעיף/הוספת הצעה לשינוי לא הופיע הטקסט המקורי - אחרי לחיצה על סוויץ' "תצוגת שינויים" הטקסט מופיע אבל ללא תצוגת ה- diff

**Comment by wonderfloyd** [comment]
https://consenz-test-environment-0.firebaseapp.com/#/

**Comment by Aharon-Porath** [comment]
How it showed:
![image](https://user-images.githubusercontent.com/5900841/69902987-7a8b5900-139c-11ea-8cbf-4a3f48cae470.png)

How it's suppose to be shown:
![image](https://user-images.githubusercontent.com/5900841/69903001-a6a6da00-139c-11ea-8e03-6599ffc3b8c2.png)

**Comment by wonderfloyd** [comment]
please check again

**Comment by Aharon-Porath** [comment]
looking good
